import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.project.deleteMany({})
  await prisma.metric.deleteMany({})

  const projects = [
    {
      id: 'master_controller',
      slug: 'master-controller',
      title: 'High-Frequency Algo Trading Suite',
      featured: true,
      description:
        'An institutional-grade quantitative trading suite powered by custom QuantumRequestOptimizer and LightningDataFetcher engines. Features high-throughput binary websocket execution, AI-driven trade post-mortems via Gemini-3-flash-preview, and automated enterprise PDF reporting.',
      techStack: ['Node.js','Binary WebSocket','Supabase','MongoDB Atlas','AWS EC2','Docker','PM2','SmartAPI','Gemini-3-flash-preview','Grafana','CloudWatch'],
      githubUrl: 'https://github.com/saikumar-bali/master_controller',
      githubProfileUrl: 'https://github.com/saikumar-bali',
      whatsappUrl: 'https://wa.me/917842204844',
      liveUrl: 'https://saikumarbali55.grafana.net/public-dashboards/e7c3902f059b44128b326eb17fb2cf4d',
      screenshots: ['/screenshots/image.png','/screenshots/Screenshot (73).png','/screenshots/Screenshot (74).png','/screenshots/Screenshot (75).png'],
      deepDive: {
        why: 'Manual trading is limited by human latency and emotional bias. I engineered this suite to achieve millisecond-level execution precision, eliminate emotional variance through trend-following SMMA logic, and provide the same level of observability found in professional hedge funds.',
        challenge: 'Managing institutional-level rate limits while maintaining high-frequency data streams. I solved this by building the QuantumRequestOptimizer for intelligent batching and the LightningDataFetcher for smart delta-fetching, reducing data overhead by 90%.',
        architecture: 'Modular Node.js architecture centered around a direct Binary WebSocket engine decoding exchange packets for near-zero latency. It leverages a hybrid database strategy (Supabase/MongoDB Atlas) and is deployed on AWS EC2 with Docker and PM2 for high-availability cluster management.',
        automation: '◆ DevOps Intelligence: Automated deployment via GitHub Actions monitoring pipelines and system health via AWS CloudWatch Logging & Alerts.\n◆ Hybrid Execution: AWS Lambda handles periodic automation tasks while PM2 manages persistent WebSocket clusters on EC2 with a Static IP.\n◆ AI Synthesis: Google Gemini-3-flash-preview analyzes closed trades and provides natural language strategic updates via Telegram.',
        monitoring: 'Live public Grafana dashboard tracking equity curves, drawdown metrics, and trade distribution in real-time. (https://saikumarbali55.grafana.net/public-dashboards/e7c3902f059b44128b326eb17fb2cf4d)',
      },
      metrics: [
        { label: 'Crash Recovery', value: '< 500ms' },
        { label: 'Data Efficiency', value: '90% Delta-Fetch' },
        { label: 'Market Scope', value: 'Multi-Index (5+)' },
        { label: 'AI Engine', value: 'Gemini-3-flash-preview' },
      ],
    },
    {
      id: 'movie_mandir',
      slug: 'movie-mandir',
      title: 'Movie Mandir — SDUI Streaming App',
      featured: true,
      description: 'A high-performance React Native CLI streaming platform with a custom Server-Driven UI (SDUI) engine. Built from the core native layer for maximum performance, the entire UI renders from a remote JSON schema. Ships with real-time admin chat and automated GitHub Actions APK releases.',
      techStack: ['React Native CLI','Android','Mobile App','TypeScript','Supabase','Cloudinary','GitHub Actions','Supabase Realtime','SDUI'],
      githubUrl: 'https://github.com/Saikumar-bali/movie_mandir',
      githubProfileUrl: 'https://github.com/saikumar-bali',
      whatsappUrl: 'https://wa.me/917842204844',
      liveUrl: 'https://github.com/Saikumar-bali/movie_mandir/releases/download/v1.0.1/movie_mandir_v1.0.1.apk',
      screenshots: ['/movie-mandir/photo_6061865890837369248_y.jpg','/movie-mandir/photo_6061865890837369249_y.jpg','/movie-mandir/photo_6061865890837369250_y.jpg','/movie-mandir/photo_6061865890837369251_y.jpg','/movie-mandir/photo_6061865890837369252_y.jpg'],
      deepDive: {
        why: 'Traditional apps are bottlenecked by store review cycles. Movie Mandir uses a high-performance React Native CLI architecture (Native Core) to ship UI changes by updating a database row — the app re-renders instantly without a new APK.',
        challenge: "Eliminating the 'Release Bottleneck.' This project was built using React Native CLI to allow for deep native-layer optimizations and custom modules that Expo doesn't support.",
        architecture: 'Built with React Native CLI for full native control. Custom JSON-to-Native bridge maps backend UI schemas to Native primitives in real-time.\n\n◆ Supabase Realtime maintains persistent, encrypted WebSocket tunnels for admin overrides and live user-admin chat synchronization.\n◆ Cloudinary pipeline auto-transcodes thumbnails based on device DPI and network jitter.',
        automation: '◆ GitHub Actions pipeline cross-compiles signed Release APKs on every merge, auto-tags releases, and deploys binaries to GitHub Releases.\n◆ Stealth-mode "Secret Channel" activation via gesture-based triggers for exclusive content.',
        monitoring: 'Edge-Driven Scalability & Performance\n\n◆ Media Optimization: Cloudinary-driven asset pipeline on-the-fly transcodes and resizes thumbnails.\n◆ Sub-Second UI Latency: Complex SDUI layouts render with < 150ms delay, providing a native-app feel with web-like flexibility.',
      },
      metrics: [
        { label: 'UI Latency', value: '< 150ms' },
        { label: 'Architecture', value: 'SDUI Engine' },
        { label: 'Delivery', value: 'Auto APK CI/CD' },
        { label: 'Backend', value: 'Supabase RT' },
      ],
    },
    {
      id: 'AAGAM_E-commerce',
      slug: 'aagam-e-commerce',
      title: 'AAGAM E-Commerce Monorepo',
      featured: true,
      description: 'Full monorepo e-commerce ecosystem with three separate client apps — Admin Panel, Customer Storefront, and Rider App — all synchronized via a single NestJS gateway with Socket.io and a centralized order state machine.',
      techStack: ['TypeScript','Next.js','NestJS','TurboRepo','PostgreSQL','Socket.io','React Native','Prisma'],
      githubUrl: 'https://github.com/saikumar-bali/AAGAM_E-commerce',
      screenshots: ['/screenshots/aagam/Capture.PNG','/screenshots/aagam/Capture2.PNG','/screenshots/aagam/Capture3.PNG'],
      deepDive: {
        why: 'Real e-commerce needs multiple actors (admin, customer, rider) working on the same order state simultaneously. I built this as a monorepo to share types, validation logic, and UI components across all three apps — guaranteeing type-safety and eliminating drift.',
        challenge: 'Orchestrating a multi-platform ecosystem with real-time state synchronization across Admin, Customer, and Rider clients — ensuring that an order status change is reflected on all three screens within milliseconds.',
        architecture: 'TurboRepo monorepo with shared packages for DTOs, UI components, and validation.\n\n◆ NestJS Gateway manages WebSocket broadcasts via Socket.io.\n◆ The order lifecycle is managed by a centralized finite state machine, making invalid transitions impossible at the type level.\n◆ Next.js for Admin and Customer; React Native (Expo) for the Rider app.',
        automation: 'Automated infrastructure deployment scripts and a centralized state machine for order lifecycle management. Shared TypeScript types auto-generate API contracts between services.',
      },
      metrics: [
        { label: 'Apps', value: '3 Clients' },
        { label: 'Architecture', value: 'TurboRepo Mono' },
        { label: 'Real-time', value: 'Socket.io' },
        { label: 'Type Safety', value: 'End-to-End' },
      ],
    },
    {
      id: 'whatsapp-ai-automation',
      slug: 'whatsapp-ai-automation',
      title: 'WhatsApp AI Automation Bot',
      featured: true,
      description: 'Intelligent WhatsApp automation bot that reads incoming messages, generates human-like responses via Groq LLM, and types them with realistic timing to bypass anti-bot detection. Includes persistent browser profiles so sessions survive restarts.',
      techStack: ['Python','Groq AI','Selenium','Stealth Mode','Browser Profiles','Llama 3'],
      githubUrl: 'https://github.com/saikumar-bali/whatsapp-ai-automation',
      screenshots: [],
      deepDive: {
        why: 'Businesses handling high message volume need AI-assisted responses that feel human. I built a stealth-mode bot that solves the hardest part — avoiding detection — through realistic keystroke simulation, randomized delays, and browser profile persistence.',
        challenge: 'Anti-bot detection during high-frequency automated messaging — WhatsApp Web aggressively fingerprints browser behavior.',
        architecture: 'Selenium in stealth mode reads DOM elements directly from WhatsApp Web.\n\n◆ Groq LLM (Llama 3) generates context-aware responses.\n◆ Custom Humanizer Engine adds variable keystroke delays, mouse movement patterns, and random idle periods.',
        automation: 'Automated context window management feeds recent conversation history to the LLM for coherent, contextual replies. Browser profile persistence means the bot never needs to re-scan the QR code after the first setup.',
      },
      metrics: [
        { label: 'Detection', value: 'Stealth Mode' },
        { label: 'LLM', value: 'Groq / Llama 3' },
        { label: 'Session', value: 'Persistent' },
        { label: 'Timing', value: 'Humanized' },
      ],
    },
    {
      id: 'erp_automation_bot',
      slug: 'erp-automation-bot',
      title: 'ERP Precision Automation Sniper',
      featured: true,
      description: 'A dual-layer high-precision automation system that uses Cloudflare Workers for sub-second REST API interactions and GitHub Actions (Playwright) as a fallback. Features "Precision Sniper" logic to achieve millisecond-level attendance accuracy with automated IST scheduling and geolocation spoofing.',
      techStack: ['Cloudflare Workers','Wrangler','Python','Playwright','GitHub Actions','Node.js','Cloudflare KV','JavaScript'],
      githubUrl: 'https://github.com/saikumar-bali/erp_automation_bot',
      screenshots: ['/screenshots/erp_automation_bot/Capture.PNG'],
      deepDive: {
        why: 'Manual attendance is prone to human error and latency. I built a "Precision Sniper" to ensure perfect 10:00:00.000 timing, bypassing geolocation locks and eliminate daily manual overhead through a serverless, self-healing architecture.',
        challenge: 'Bypassing complex CSRF protection and geolocation-fenced REST APIs while maintaining sub-second execution speed across varying network conditions.',
        architecture: 'Dual-Layer execution: \n\n◆ Primary: Cloudflare Worker interacts directly with the ERP REST API for zero-latency execution.\n◆ Secondary: GitHub Actions runs a Playwright headless browser as a fallback to simulate real user behavior.\n◆ Pre-Warm Logic: The system wakes up 60 seconds early to handle authentication and session setup, ensuring the final "punch" happens at the exact millisecond.',
        automation: '◆ Geolocation spoofing injects specific GPS coordinates at the API level.\n◆ Automated IST-aware scheduling with holiday synchronization.\n◆ Live glassmorphic dashboard for real-time monitoring and mode switching (Work/Leave).\n◆ Pre-authentication pipeline eliminates login-time variability.',
      },
      metrics: [
        { label: 'Precision', value: 'Millisecond Level' },
        { label: 'Method', value: 'Serverless API' },
        { label: 'Accuracy', value: '10:00:00.005' },
        { label: 'Platform', value: 'Cloudflare / GH' },
      ],
    },
    {
      id: 'reel_genius-ai',
      slug: 'reelgenius-ai',
      title: 'ReelGenius AI',
      featured: false,
      description: 'Browser-side AI video creator — paste text or lyrics, and it auto-generates timestamps with Gemini-3-flash-preview, synchronizes them to audio via Web Audio API, adds cinematic transitions, and exports an MP4 using MediaRecorder. No server required.',
      techStack: ['TypeScript','React','Gemini-3-flash-preview','Web Audio API','MediaRecorder','Canvas API'],
      githubUrl: 'https://github.com/saikumar-bali/reel_genius_ai',
      liveUrl: 'https://reel-genius-ai.onrender.com',
      screenshots: ['/screenshots/reel_genius/1.PNG'],
      deepDive: {
        why: 'Content creators waste hours syncing lyrics to music manually. ReelGenius automates timestamp generation and visual sync entirely in the browser using AI.',
        challenge: 'Complex browser-side audio/video processing without server-side rendering — Web Audio API, Canvas compositing, and MediaRecorder must work in perfect sync.',
        architecture: 'Gemini-3-flash-preview generates lyric timestamps from raw text.\n◆ Web Audio API analyzes the track for beat timing.\n◆ Canvas API composites text overlays frame-by-frame.\n◆ MediaRecorder captures the final composited stream as MP4.',
        automation: 'AI-powered lyric timestamping eliminates manual sync work. Automated cinematic transitions selected based on lyric sentiment analysis.',
      },
      metrics: [
        { label: 'AI Engine', value: 'Gemini-3-flash-preview' },
        { label: 'Output', value: 'MP4 Export' },
        { label: 'Server', value: 'Zero (Browser)' },
        { label: 'Sync', value: 'AI Timestamped' },
      ],
    },
    {
      id: 'cine_verse',
      slug: 'cineverse',
      title: 'CineVerse',
      featured: false,
      description: 'Modern movie and series discovery PWA with search, filters, and streaming integration. Includes a custom stream broker to handle provider-side CORS restrictions and Supabase backend.',
      techStack: ['React','TypeScript','Supabase','PWA','Stream Broker'],
      githubUrl: 'https://github.com/saikumar-bali/cine_verse',
      liveUrl: 'https://cine-verse-v3fs.onrender.com',
      screenshots: ['/screenshots/cine_verse/Capture.PNG'],
      deepDive: {
        why: 'Existing movie discovery apps either have poor UIs or no streaming integration. CineVerse is a proper PWA with a custom stream broker solving the CORS problem.',
        challenge: 'Provider-side IP and CORS restrictions block media streams from loading in browsers.',
        architecture: 'React + Supabase for catalog and user state.\n◆ Custom Stream Broker negotiates provider tokens and proxies the stream manifest with correct headers.',
        automation: 'Automated catalog ingestion from provider APIs with resilient error handling and incremental sync.',
      },
      metrics: [
        { label: 'Type', value: 'PWA' },
        { label: 'Backend', value: 'Supabase' },
        { label: 'Streaming', value: 'Custom Broker' },
        { label: 'Offline', value: 'Supported' },
      ],
    },
    {
      id: 'jy_defence_acadamy',
      slug: 'jy-defence-academy',
      title: 'JY Defence Academy',
      featured: false,
      description: 'Interactive educational portal for defence aspirants with a military-grade HUD aesthetic, animated SVG radar components, type-safe TanStack routing, and real-time Framer Motion orchestration throughout.',
      techStack: ['TypeScript','React','TanStack Router','Framer Motion','Shadcn UI','SVG HUD'],
      githubUrl: 'https://github.com/saikumar-bali/jy_defence_acadamy',
      liveUrl: 'https://jy-defence-acadamy.onrender.com',
      screenshots: ['/screenshots/jy_defence_academy/Capture.PNG'],
      deepDive: {
        why: 'Defence preparation students need a platform that is both authoritative in aesthetic and smooth in navigation. I built the HUD radar component from scratch using SVG + Framer Motion.',
        challenge: 'Building a high-fidelity interactive educational portal with complex routing, animated HUD components, and immersive motion design that performs well on mobile.',
        architecture: 'React + TanStack Router for type-safe, file-based routing.\n◆ Custom SVG Radar HUD Component with Framer Motion animation.\n◆ Shadcn UI primitives styled to match the military aesthetic.',
        automation: 'Automated type-safe route generation prevents 404s at compile time.',
      },
      metrics: [
        { label: 'Routing', value: 'TanStack' },
        { label: 'Animation', value: 'Framer Motion' },
        { label: 'HUD', value: 'Custom SVG' },
        { label: 'UI Kit', value: 'Shadcn' },
      ],
    },
    {
      id: 'beauty-salon',
      slug: 'beauty-salon',
      title: 'Beauty Salon Website',
      featured: false,
      description: 'High-performance salon booking website with animated service showcases, mobile-first design, and an automated image optimization pipeline that converts assets to WebP and generates responsive breakpoints at build time.',
      techStack: ['React','MUI','Framer Motion','Sharp','WebP'],
      githubUrl: 'https://github.com/saikumar-bali/beauty-salon',
      screenshots: [],
      deepDive: {
        why: 'Salon websites are image-heavy and typically load slowly on mobile. I solved this with a pre-build optimization hook that converts all images to WebP and generates multiple responsive sizes.',
        challenge: 'High-resolution asset delivery causing performance bottlenecks on mobile networks.',
        architecture: 'Sharp-powered image optimization pipeline runs before each build.\n◆ React lazy loading handles component-level code splitting.\n◆ CDN delivery for all static assets.',
        automation: 'Pre-build hook automatically converts all images to WebP and generates responsive srcsets. Zero manual image resizing needed.',
      },
      metrics: [
        { label: 'Images', value: 'Auto WebP' },
        { label: 'Loading', value: 'Lazy Split' },
        { label: 'Mobile', value: 'First Design' },
        { label: 'Delivery', value: 'CDN' },
      ],
    },
    {
      id: 'messaging_app',
      slug: 'messaging-app',
      title: 'SMS Interceptor & API Forwarder',
      featured: true,
      description: 'A specialized Android security tool that registers as the Default SMS Application to intercept, delete, and forward incoming messages to custom API endpoints. Features native Kotlin Broadcast Receivers for instant OTP filtering and system-level message suppression.',
      techStack: ['React Native','Kotlin','Android Native','Broadcast Receivers','SharedPreferences','Content Providers'],
      githubUrl: 'https://github.com/saikumar-bali/messaging_app',
      liveUrl: 'https://github.com/Saikumar-bali/messaging_app/releases/download/v1.0.01/app-x86_64-release.apk',
      screenshots: ['/screenshots/messaging_app/photo_6068637903211926848_y.jpg','/screenshots/messaging_app/photo_6068637903211926849_y.jpg'],
      deepDive: {
        why: "Standard automation tools cannot intercept SMS at the system level. I built this to solve the 'Instant suppression' problem — deleting security-critical messages (like OTPs) before the system even creates a notification, while simultaneously forwarding the payload to a remote server.",
        challenge: "Navigating Android's high-permission requirements. The app must successfully register as the Default SMS App to receive the `SMS_DELIVER` broadcast, which is otherwise inaccessible to standard applications.",
        architecture: "Native `SmsReceiver.kt` listens for system-level SMS broadcasts.\n\n◆ Direct integration with the `content://sms/` provider allows for sub-second message deletion by ID.\n◆ `SharedPreferences` manages persistent API configurations and filter states.\n◆ Built using React Native CLI with a custom Kotlin bridge for high-priority message processing.",
        automation: "◆ Instant deletion logic suppresses system notifications for blocked messages.\n◆ Automated API forwarding sends SMS payloads to a user-defined URL in the background.\n◆ Specialized OTP detection mode filters and extracts verification codes automatically.",
      },
      metrics: [
        { label: 'Latency', value: 'Sub-second' },
        { label: 'Android Ver', value: '10 - 14' },
        { label: 'Method', value: 'Default SMS App' },
        { label: 'Security', value: 'OTP Filtering' },
      ],
    },
    {
      id: 'hippocloud-elevate',
      slug: 'hippocloud-elevate',
      title: 'HippoCloud Elevate — 3D Portal',
      featured: false,
      description: 'Enterprise 3D visualization portal with post-processing effects (bloom, SSAO) using React Three Fiber and WebGL. Includes a LOD system and automated 3D asset compression pipeline for performance on low-end devices.',
      techStack: ['React','Three.js','React Three Fiber','WebGL','Post-processing','LOD'],
      githubUrl: 'https://github.com/saikumar-bali/hippocloud-elevate',
      screenshots: [],
      deepDive: {
        why: 'HippoCloud wanted a 3D product visualization to differentiate from competitors. I built a WebGL scene with post-processing and an LOD system that keeps 60fps on budget devices.',
        challenge: 'Rendering complex 3D scenes with post-processing effects on low-end mobile devices.',
        architecture: 'React Three Fiber for declarative 3D scene management.\n◆ Post-processing pipeline with bloom and vignette.\n◆ Custom LOD system switches mesh complexity based on device GPU tier.',
        automation: 'Automated 3D asset compression pipeline reduces GLTF file sizes by 60-80%.',
      },
      metrics: [
        { label: 'Renderer', value: 'React Three Fiber' },
        { label: 'Effects', value: 'Post-Processing' },
        { label: 'LOD', value: 'Auto GPU Tier' },
        { label: 'Asset Size', value: '-60% GLTF' },
      ],
    },
    {
      id: 'vaji_news',
      slug: 'vaji-news',
      title: 'Vaji News Platform',
      featured: false,
      description: 'Next.js-based automated news aggregation and publishing platform with Prisma/PostgreSQL backend, SSR for SEO, and a content pipeline that deduplicates and normalizes articles from multiple sources.',
      techStack: ['TypeScript','Next.js','Prisma','PostgreSQL','SSR'],
      githubUrl: 'https://github.com/saikumar-bali/vaji_news',
      liveUrl: 'https://vaji-news.vercel.app/login',
      screenshots: ['/screenshots/vaji_news/vaji_news.PNG'],
      deepDive: {
        why: 'A robust news platform needs both SEO-friendly SSR and a reliable ingestion pipeline.',
        challenge: 'Aggregating and normalizing news from multiple heterogeneous sources with different content structures and duplicate detection needs.',
        architecture: 'Next.js with SSR for SEO.\n◆ Prisma + PostgreSQL for persistent article storage.\n◆ Deduplication uses article fingerprinting on title and content hash.',
        automation: 'Automated content fetching with scheduled updates. Built-in data deduplication prevents duplicate articles.',
      },
      metrics: [
        { label: 'Rendering', value: 'SSR / SEO' },
        { label: 'ORM', value: 'Prisma' },
        { label: 'Dedup', value: 'Content Hash' },
        { label: 'Schedule', value: 'Auto Ingestion' },
      ],
    },
    {
      id: 'news_website',
      slug: 'news-website',
      title: 'Telugu News Aggregator',
      featured: false,
      description: 'Automated Telugu news aggregation platform scraping 20+ sources using Netlify Serverless Functions triggered by GitHub Actions cron jobs, with Firebase storage and a Svelte frontend.',
      techStack: ['Svelte','Netlify Functions','Web Scraping','Firebase','GitHub Actions'],
      githubUrl: 'https://github.com/saikumar-bali/news_website',
      liveUrl: 'https://news-website-2ev.pages.dev/',
      screenshots: ['/screenshots/telugu_news_aggregator/Capture.PNG'],
      deepDive: {
        why: 'Telugu news is scattered across dozens of sites. I built a serverless pipeline that automatically scrapes, deduplicates, and publishes articles with zero ongoing manual effort.',
        challenge: 'Aggregating and normalizing news from 20+ heterogeneous sources with varied HTML structures, paywalls, and rate limits.',
        architecture: 'Svelte SPA for the frontend.\n◆ Netlify Functions handle scraping per-source.\n◆ GitHub Actions cron triggers scraping jobs every hour.\n◆ Firebase stores the normalized article data.',
        automation: 'Automated serverless scraping pipeline with content deduplication, broken source alerting, and scheduled re-runs via GitHub Actions cron.',
      },
      metrics: [
        { label: 'Sources', value: '20+ Scraped' },
        { label: 'Trigger', value: 'GH Actions Cron' },
        { label: 'Storage', value: 'Firebase' },
        { label: 'Server', value: 'Netlify Functions' },
      ],
    },
    {
      id: 'paatala_pustakam_studio',
      slug: 'paatala-pustakam-studio',
      title: 'Paatala Pustakam Studio',
      featured: false,
      description: 'Content management studio for bookstore operations — book listings, inventory scheduling, SEO metadata generation, and rich text editing. Built with Next.js + Prisma + PostgreSQL.',
      techStack: ['TypeScript','Next.js','Prisma','PostgreSQL','Rich Text'],
      githubUrl: 'https://github.com/saikumar-bali/paatala_pustakam_studio',
      liveUrl: 'https://paatala-pustakam-studio.onrender.com',
      screenshots: ['/screenshots/patala_pustrakam_studio/Capture.PNG'],
      deepDive: {
        why: 'Bookstore staff needed a simple CMS to manage listings without touching code. I built a studio-style interface with rich text editing and one-click publishing.',
        challenge: 'Building a comprehensive CMS for bookstore operations with an intuitive interface for non-technical users.',
        architecture: 'Next.js + Prisma + PostgreSQL + Rich text editor integration.',
        automation: 'Automated content scheduling and SEO metadata generation for book listings. Bulk import from CSV for inventory.',
      },
      metrics: [
        { label: 'CMS', value: 'Studio UI' },
        { label: 'ORM', value: 'Prisma' },
        { label: 'SEO', value: 'Auto Meta' },
        { label: 'Import', value: 'CSV Bulk' },
      ],
    },
    {
      id: 'patala_pustakam_website',
      slug: 'patala-pustakam-website',
      title: 'Patala Pustakam Bookstore',
      featured: false,
      description: 'Full-stack bookstore e-commerce with a hybrid backend — complex order processing on Express/Node.js and performance-critical catalog delivery on Cloudflare Workers at the edge.',
      techStack: ['React','TypeScript','Express','Cloudflare Workers','Prisma','PostgreSQL'],
      githubUrl: 'https://github.com/saikumar-bali/patala_pustakam_website',
      liveUrl: 'https://patala-pusthakam.onrender.com',
      screenshots: ['/screenshots/patala_pustakam_bookstore/Capture.PNG','/screenshots/patala_pustakam_bookstore/Capture2.PNG'],
      deepDive: {
        why: 'Bookstore e-commerce has two distinct performance profiles: catalog browsing (needs edge latency) and order processing (needs complex business logic). I separated these architecturally.',
        challenge: 'Architecting a hybrid backend balancing complex order logic with edge-delivered catalog performance.',
        architecture: 'React frontend + Express for order management with Prisma ORM.\n◆ Cloudflare Workers for catalog, search, and product delivery at the edge.\n◆ PostgreSQL as the source of truth.',
        automation: 'Automated admin workflows for bulk inventory management. Edge-side order notification triggers via Cloudflare Workers.',
      },
      metrics: [
        { label: 'Edge', value: 'CF Workers' },
        { label: 'Orders', value: 'Express ORM' },
        { label: 'Catalog', value: 'Edge Delivery' },
        { label: 'DB', value: 'PostgreSQL' },
      ],
    },
    {
      id: 'hippoclouds_website',
      slug: 'hippoclouds-website',
      title: 'HippoClouds Website',
      featured: false,
      description: 'Enterprise SaaS product showcase portal for HippoClouds Technologies featuring modular multi-product architecture (CRM, HRM, Mint), animated UI, and an AI-driven live chat assistant with CRM webhook integration.',
      techStack: ['React','JavaScript','Styled Components','Context API','Framer Motion','AI Chat'],
      githubUrl: 'https://github.com/saikumar-bali/hippoclouds_website',
      liveUrl: 'https://hippoclouds-website.onrender.com',
      screenshots: ['/screenshots/hippoclouds_website/Capture.PNG'],
      deepDive: {
        why: 'HippoClouds needed a website presenting multiple enterprise products without feeling cluttered, with an AI chatbot to qualify leads.',
        challenge: 'Building a modular, multi-tenant enterprise portal to showcase diverse SaaS products while maintaining a cohesive brand identity.',
        architecture: 'React + Styled Components with a product-aware Context API.\n◆ Each product module is lazy-loaded.\n◆ Framer Motion handles page transitions and scroll-triggered animations.',
        automation: 'Automated lead capture with integrated CRM webhooks. AI-driven live chat assistant qualifies visitor intent and routes high-intent leads to the sales team.',
      },
      metrics: [
        { label: 'Products', value: 'CRM/HRM/Mint' },
        { label: 'Leads', value: 'AI Chatbot' },
        { label: 'Load', value: 'Lazy Modules' },
        { label: 'Animation', value: 'Framer Motion' },
      ],
    },
    {
      id: 'bill_tracker',
      slug: 'bill-tracker',
      title: 'Bill Tracker',
      featured: false,
      description: 'Real-time expense and bill tracking app with WebSocket-powered live updates, automated bill categorization, and recurring payment detection with custom rule engine.',
      techStack: ['React','Node.js','PostgreSQL','WebSocket'],
      githubUrl: 'https://github.com/saikumar-bali/bill_tracker',
      liveUrl: 'https://bill-tracker.saikumarbali555.workers.dev/',
      screenshots: [],
      deepDive: {
        why: 'Personal finance apps miss the key feature: alerting you about bills you forgot. I built automated recurring detection that identifies patterns in your expense history.',
        challenge: 'Real-time expense tracking with automated categorization and intelligent recurring payment detection.',
        architecture: 'React frontend with WebSocket for live balance updates.\n◆ Node.js backend with a rule-based categorization engine.\n◆ PostgreSQL stores transaction history with indexed queries for pattern detection.',
        automation: 'Automated recurring payment detection using time-series pattern analysis. Rule-based categorization auto-tags expenses.',
      },
      metrics: [
        { label: 'Real-time', value: 'WebSocket' },
        { label: 'Categories', value: 'Auto Tagged' },
        { label: 'Recurring', value: 'Pattern AI' },
        { label: 'Alerts', value: 'Pre-due' },
      ],
    },
    {
      id: 'chat_bot',
      slug: 'chat-bot',
      title: 'AI Customer Support Chatbot',
      featured: false,
      description: 'AI-powered customer support chatbot with GPT integration, Redis-backed session memory for long-term context management, and automated triage with intelligent escalation to human agents.',
      techStack: ['Node.js','Express','GPT','Redis','TypeScript'],
      githubUrl: 'https://github.com/saikumar-bali/chat_bot',
      screenshots: [],
      deepDive: {
        why: 'Customer support bots that lose context frustrate users. I built a Redis-backed context window that persists conversation history across sessions.',
        challenge: 'Maintaining long-term conversation context and session memory across interactions.',
        architecture: 'Express session + GPT integration + Redis cache layer for context window management.',
        automation: 'Automated triage with intelligent routing and escalation workflows. Unresolved tickets auto-escalated after N failed attempts.',
      },
      metrics: [
        { label: 'Context', value: 'Redis Backed' },
        { label: 'LLM', value: 'GPT' },
        { label: 'Triage', value: 'Auto Route' },
        { label: 'Escalation', value: 'Smart Handoff' },
      ],
    },
    {
      id: 'telegram_backup',
      slug: 'telegram-backup',
      title: 'Telegram Backup Tool',
      featured: false,
      description: 'Python tool that performs incremental encrypted backups of Telegram messages and media, respecting rate limits, and uploads compressed archives to cloud storage on a schedule.',
      techStack: ['Python','Telegram API','SQLite','Cloud Storage'],
      githubUrl: 'https://github.com/saikumar-bali/telegram_backup',
      screenshots: [],
      deepDive: {
        why: 'Telegram does not provide an easy way to export message history programmatically. I built this for GDPR-compliant message archives.',
        challenge: 'Reliable backup of Telegram messages and media while respecting API rate limits.',
        architecture: 'Python + Telethon for MTProto API access.\n◆ SQLite for local incremental state tracking.\n◆ Compressed and encrypted archives uploaded to cloud storage.',
        automation: 'Automated incremental backups with rate-limit backoff. Encryption and compression applied automatically. Scheduled via cron.',
      },
      metrics: [
        { label: 'Protocol', value: 'MTProto' },
        { label: 'State', value: 'Incremental' },
        { label: 'Security', value: 'Encrypted' },
        { label: 'Schedule', value: 'Cron' },
      ],
    },
    {
      id: 'vaji_one_launch',
      slug: 'vaji-one-launch',
      title: 'Vaji One — Product Launch Page',
      featured: false,
      description: 'High-conversion product launch landing page with advanced Framer Motion scroll animations, A/B testing integration, and conversion tracking setup. Built for maximum impact on day one.',
      techStack: ['React','Framer Motion','TypeScript','A/B Testing'],
      githubUrl: 'https://github.com/saikumar-bali/vaji_one_launch',
      liveUrl: 'https://vaji-one-launch.onrender.com',
      screenshots: [],
      deepDive: {
        why: 'Product launches have one job: convert visitors to signups. Every element was designed with conversion psychology in mind.',
        challenge: 'Creating a high-performance launch page with complex scroll-triggered animations without sacrificing Lighthouse scores.',
        architecture: 'React + Framer Motion with intersection-observer-based animation triggers. A/B testing SDK integrated for CTA variant testing.',
        automation: 'Automated A/B test variant assignment and conversion tracking. Analytics event firing on all key interactions.',
      },
      metrics: [
        { label: 'Purpose', value: 'High Conversion' },
        { label: 'Animation', value: 'Scroll Triggered' },
        { label: 'Testing', value: 'A/B Variants' },
        { label: 'Tracking', value: 'Analytics' },
      ],
    },
    {
      id: 'sharp_computers',
      slug: 'sharp-computers',
      title: 'Sharp Computers Website',
      featured: false,
      description: 'Responsive static website for a computer retail and service business. Built with HTML/CSS/JS with CDN delivery, optimized Core Web Vitals, and automated image optimization.',
      techStack: ['HTML','CSS','JavaScript','CDN'],
      githubUrl: 'https://github.com/Saikumar-bali/sharp_computers',
      liveUrl: 'https://saikumar-bali.github.io/sharp_computers/',
      screenshots: ['/screenshots/sharp_computers/Capture.PNG'],
      deepDive: {
        why: 'Small businesses need fast, reliable websites that rank on Google and work on every device.',
        challenge: 'Building a fast, SEO-optimized static site for a local business that works well on 2G/3G connections.',
        architecture: 'Static HTML/CSS/JS with CDN delivery. Minified and concatenated bundles. Lazy-loaded images.',
        automation: 'Automated image optimization and responsive breakpoint generation.',
      },
      metrics: [
        { label: 'Type', value: 'Static CDN' },
        { label: 'SEO', value: 'Core Web Vitals' },
        { label: 'Images', value: 'Auto Optimized' },
        { label: 'Mobile', value: '2G Ready' },
      ],
    },
    {
      id: 'hippo_chat',
      slug: 'hippo-chat',
      title: 'Hippo Chat',
      featured: false,
      description: 'Real-time chat system with Socket.io, Redis adapter for multi-instance scaling, optimistic UI updates, and automated message delivery receipts with intelligent reconnection handling.',
      techStack: ['Node.js','Express','Socket.io','Redis'],
      githubUrl: 'https://github.com/saikumar-bali/hippo_chat',
      screenshots: [],
      deepDive: {
        why: 'Most real-time chat demos do not handle the hard cases: unstable connections, multiple server instances, and message ordering. I built Hippo Chat to properly solve these.',
        challenge: 'Maintaining real-time message synchronization across unstable network conditions and multiple server instances.',
        architecture: 'Node.js + Socket.io + Redis adapter for horizontal scaling.\n◆ Optimistic UI updates send messages instantly and reconcile server acknowledgment.',
        automation: 'Automated message delivery receipts. Intelligent reconnection with backoff — missed messages are fetched on reconnect.',
      },
      metrics: [
        { label: 'Scale', value: 'Redis Adapter' },
        { label: 'UI', value: 'Optimistic' },
        { label: 'Delivery', value: 'Read Receipts' },
        { label: 'Recovery', value: 'Auto Reconnect' },
      ],
    },
  ]

  for (const project of projects) {
    await prisma.project.create({ data: project })
    console.log(`  ✓ ${project.title}`)
  }

  await prisma.metric.create({
    data: { id: 'system-status', label: 'System Status', value: 'Operational', type: 'status' },
  })

  console.log('\n✅ Database seeded successfully — ' + projects.length + ' projects loaded.')
}

main()
  .catch((e) => { console.error('Seed error:', e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
